const ActionTypes = {
    ADD: "ADD",
    SETWORKERS:'SETWORKERS',
    SETPARTICULARCLIENTS:'SETPARTICULARCLIENTS',
    SETUSER :"SETUSER",
    SETTOKEN:'SETTOKEN',
    SETSTUDENT:'SETSTUDENT',
    SETLOGOUT:'SETLOGOUT',
    SETLOADING:'SETLOADING',
    SETAUTHENTICATION:'SETAUTHENTICATION',
    SETSHOWHEADERBUTTON:'SETSHOWHEADERBUTTON',
    SETHEADERBUTTONVALUE:'SETHEADERBUTTONVALUE',
    SETTABLEXI:'SETTABLEXI',
    SETTABLEXII:'SETTABLEXII',
    SETSUBJECTXI:'SETSUBJECTXI',
    SETSUBJECTXII:'SETSUBJECTXII',
    SETINSTRUCTORS:'SETINSTRUCTORS',
    SETCURRENTTABLEXI:'SETCURRENTTABLEXI',
    SETCURRENTTABLEXII:'SETCURRENTTABLEXII'
}
export default ActionTypes